# Azure OpenAI Credentials
AZURE_OPENAI_ENDPOINT="YOUR_AZURE_OPENAI_ENDPOINT"
AZURE_OPENAI_API_KEY="YOUR_AZURE_OPENAI_API_KEY"
AZURE_OPENAI_DEPLOYMENT_NAME="YOUR_GPT_DEPLOYMENT_NAME"
AZURE_OPENAI_API_VERSION="2024-02-01"

# Azure AI Search Credentials
AZURE_SEARCH_ENDPOINT="https://[your-service-name].search.windows.net"
AZURE_SEARCH_INDEX="teams-calls"
AZURE_SEARCH_KEY="YOUR_AZURE_AI_SEARCH_API_KEY"
